services:
  etcd:
    image: 'docker.io/bitnami/etcd:latest'
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=gomall
      - MYSQL_USER=gomall
      - MYSQL_PASSWORD=gomall
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  nats:
    image: 'nats:latest'
    ports:
      - 4222:4222
      - 8222:8222
