services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=gomall
      - MYSQL_USER=gomall
      - MYSQL_PASSWORD=gomall
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
